package client

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/jmoiron/sqlx"
)

// Bridge exposes dynamically typed methods for language runtimes. Every method
// accepts a context and returns a value plus an error so runtimes can inject the
// context and surface errors consistently.
type Bridge struct {
	client *Client
}

// NewBridge creates a dynamic-language bridge from an existing connection pool.
func NewBridge(db *sqlx.DB) *Bridge {
	return &Bridge{client: NewClient(db)}
}

// WithObserver sets an observer on the underlying client.
func (b *Bridge) WithObserver(fn ObserveFunc) {
	b.client.WithObserver(fn)
}

// Insert inserts a dynamically typed named value.
func (b *Bridge) Insert(ctx context.Context, table string, value any) (any, error) {
	err := b.client.Insert(ctx, table, value)
	return err == nil, err
}

// Replace replaces a row using a dynamically typed named value.
func (b *Bridge) Replace(ctx context.Context, table string, value any) (any, error) {
	err := b.client.Replace(ctx, table, value)
	return err == nil, err
}

// Update updates a row using dynamically typed named values and key columns.
func (b *Bridge) Update(ctx context.Context, table string, value any, keyColumns ...any) (any, error) {
	keys := make([]string, len(keyColumns))
	for i, key := range keyColumns {
		keys[i] = fmt.Sprint(key)
	}
	err := b.client.Update(ctx, table, value, keys...)
	return err == nil, err
}

// Query executes a statement with dynamically typed arguments.
func (b *Bridge) Query(ctx context.Context, query string, args ...any) (any, error) {
	err := b.client.Query(ctx, query, args...)
	return err == nil, err
}

// Get returns the first result row.
func (b *Bridge) Get(ctx context.Context, query string, args ...any) (any, error) {
	rows, err := b.queryMaps(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return nil, sql.ErrNoRows
	}
	return rows[0], nil
}

// GetAll returns all result rows.
func (b *Bridge) GetAll(ctx context.Context, query string, args ...any) (any, error) {
	return b.queryMaps(ctx, query, args...)
}

// Connect reserves an exclusive connection from the pool.
func (b *Bridge) Connect(ctx context.Context) (any, error) {
	err := b.client.Connect(ctx)
	return err == nil, err
}

// Close releases an exclusive connection back to the pool.
func (b *Bridge) Close(context.Context) (any, error) {
	err := b.client.Close()
	return err == nil, err
}

// Begin starts a transaction.
func (b *Bridge) Begin(ctx context.Context) (any, error) {
	err := b.client.Begin(ctx)
	return err == nil, err
}

// Rollback rolls back the active transaction.
func (b *Bridge) Rollback(context.Context) (any, error) {
	err := b.client.Rollback()
	return err == nil, err
}

// Commit commits the active transaction.
func (b *Bridge) Commit(context.Context) (any, error) {
	err := b.client.Commit()
	return err == nil, err
}

// Insert_id returns the ID generated by the last insert.
func (b *Bridge) InsertID(context.Context) (any, error) {
	return b.client.InsertID(), nil
}

// Rows_affected returns the affected row count from the last write.
func (b *Bridge) RowsAffected(context.Context) (any, error) {
	return b.client.RowsAffected(), nil
}

func (b *Bridge) queryMaps(ctx context.Context, query string, args ...any) ([]map[string]any, error) {
	q, boundArgs, logArgs, err := b.client.prepareQuery(query, args...)
	if err != nil {
		return nil, fmt.Errorf("%w\nquery: %s", err, query)
	}

	started := time.Now()
	rows, err := b.queryRows(ctx, q, boundArgs...)
	if err != nil {
		b.client.log(ctx, query, logArgs, started, err)
		return nil, fmt.Errorf("%w\nquery: %s", err, query)
	}
	defer rows.Close()

	result := make([]map[string]any, 0)
	for rows.Next() {
		row := make(map[string]any)
		if err = rows.MapScan(row); err != nil {
			b.client.log(ctx, query, logArgs, started, err)
			return nil, fmt.Errorf("%w\nquery: %s", err, query)
		}
		for column, value := range row {
			if bytes, ok := value.([]byte); ok {
				row[column] = string(bytes)
			}
		}
		result = append(result, row)
	}
	if err = rows.Err(); err != nil {
		b.client.log(ctx, query, logArgs, started, err)
		return nil, fmt.Errorf("%w\nquery: %s", err, query)
	}
	b.client.log(ctx, query, logArgs, started, nil)
	return result, nil
}

func (b *Bridge) queryRows(ctx context.Context, query string, args ...any) (*sqlx.Rows, error) {
	if b.client.tx != nil {
		return b.client.tx.QueryxContext(ctx, query, args...)
	}
	if b.client.conn != nil {
		return b.client.conn.QueryxContext(ctx, query, args...)
	}
	return b.client.db.QueryxContext(ctx, query, args...)
}
